INSERT INTO menu (MenuType, Course, CourseDescription, CoursePrice) 
VALUES 
    ('Drinks', 'Sapporo beer', 'A Japanese lager beer, popularly served with sushi and other Japanese dishes.', 7),
    ('Drinks', 'Asahi beer', 'Another popular Japanese lager beer.', 6),
    ('Drinks', 'Sake', 'A traditional Japanese rice wine that is often served warm or cold with sushi and other Japanese dishes.', 9),
    ('Drinks', 'Plum wine', 'A sweet, fruity wine made with plums, often served chilled as an accompaniment to sushi and other Japanese dishes.', 9),
    ('Drinks', 'Green tea', 'A traditional Japanese tea with a delicate, grassy flavor, often served hot or cold.', 5),
    ('Drinks', 'Matcha green tea', 'A finely ground, powdered green tea with a slightly bitter, earthy flavor, often served as a hot tea or in ice cream or lattes.', 6),
    ('Drinks', 'Iced tea', 'A refreshing, non-alcoholic option, often served sweetened or unsweetened.', 4),
    ('Drinks', 'Lemonade', 'A refreshing, non-alcoholic option, often served sweetened or unsweetened.', 4),
    ('Drinks', 'Soft drinks', 'A variety of non-alcoholic, carbonated beverages such as Coke, Sprite, and Ginger Ale.', 3),
    ('Drinks', 'Mineral water', 'A non-alcoholic option, often served sparkling or still.', 2),
    ('Appetizers', 'Edamame', 'Boiled and lightly salted soybeans served in the pod.', 5),
    ('Appetizers', 'Gyoza', 'Pan-fried dumplings filled with meat or vegetables.', 6),
    ('Appetizers', 'Age tofu', 'Deep-fried tofu served with a side of tempura sauce.', 5),
    ('Appetizers', 'Sunomono', 'Thinly sliced raw fish or vegetables marinated in vinegar.', 7),
    ('Appetizers', 'Takoyaki', 'Ball-shaped snack filled with diced octopus and topped with green onion and a special sauce.', 7),
    ('Appetizers', 'Ebi fry', 'Fried prawns served with a side of tonkatsu sauce.', 9),
    ('Appetizers', 'Okonomiyaki', 'Grilled savory pancake filled with vegetables and seafood or meat, topped with a special sauce and green onion.', 10),
    ('Appetizers', 'Sashimi', 'Thinly sliced raw fish served with a side of soy sauce and wasabi.', 12),
    ('Starters', 'Miso soup', 'A traditional Japanese soup made with miso paste, tofu, and green onions.', 3),
    ('Starters', 'Tsukemono', 'A selection of pickled vegetables served as an appetizer.', 5),
    ('Starters', 'Tako wasabi', 'Thinly sliced octopus mixed with wasabi and soy sauce.', 7),
    ('Starters', 'Asari no sake gaki', 'Grilled asari clams seasoned with sake and salt.',  8),
    ('Starters', 'Nasu dengaku', 'Grilled eggplant topped with a sweet miso glaze.',  6),
    ('Starters', 'Yakiniku', 'Grilled beef skewers served with a side of ponzu sauce.',  9),
    ('Starters', 'Ebi fry', 'Fried prawns served with a side of tonkatsu sauce.',  9),
    ('Starters', 'Ika no karaage', 'Fried squid served with a side of lemon wedges.',  10),
    ('Main course', 'California roll', 'A classic roll filled with imitation crab meat, avocado, and cucumber.',  10),
    ('Main course', 'Tekka maki', 'Thinly sliced raw tuna rolled with rice and seaweed.', 12),
    ('Main course', 'Ebi tempura roll', 'A roll filled with deep-fried prawns and vegetables.', 14),
    ('Main course', 'Spicy tuna roll', 'A roll filled with spicy tuna and vegetables.', 12),
    ('Main course', 'Unagi roll', 'A roll filled with grilled eel and cucumber.', 15),
    ('Main course', 'Philadelphia roll', 'A roll filled with cream cheese, smoked salmon, and avocado.', 12),
    ('Main course', 'Chirashi', 'A bowl of sushi rice topped with a variety of sliced raw fish and vegetables.', 20),
    ('Main course', 'Sashimi platter', 'A platter of thinly sliced raw fish served with a side of soy sauce and wasabi.', 25),
    ("Desserts", "Mochi ice cream", "A ball of ice cream wrapped in a layer of soft, chewy mochi.", 5),
    ("Desserts", "Green tea ice cream", "A classic Japanese ice cream flavor made with matcha green tea.", 5),
    ("Desserts", "Black sesame ice cream", "A creamy, nutty ice cream made with black sesame seeds.", 5),
    ("Desserts", "Matcha cheesecake", "A creamy cheesecake flavored with matcha green tea.", 7),
    ("Desserts", "Mango pudding", "A creamy, smooth pudding made with mango puree.", 6),
    ("Desserts", "Anmitsu", "A traditional Japanese dessert made with agar agar jelly, red bean paste, and fruit.", 8),
    ("Desserts", "Matcha parfait", "A layered dessert featuring matcha green tea ice cream, mochi, and fruit.", 9),
    ("Desserts", "Yuzu sorbet", "A refreshing sorbet made with yuzu citrus fruit.", 6);

